# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 of the host
    environment:
      NODE_ENV: production